config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  
  root 'pins#index' #Creates root_path

  get 'about' => 'pages#about' #Creates about_path

  get 'contact_us' => 'pages#contact' #url is 'contact_us'; file is 'contact' in pages folder AND in pages_controller def 'contact'

  get 'our_prices' => 'pages#pricing'
  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
	
	validates :image, presence: true
	validates :description, presence: true
	
     
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :pins
  
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	before_filter :configure_permitted_parameters, if: :devise_controller?

	protected
	
	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) << :name
		devise_parameter_sanitizer.for(:account_update) << :name
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
  
  def pricing
  end
  
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /pins
  def index
    @pins = Pin.all.order("created_at DESC").paginate(page: params[:page], per_page: 5)
  end

  # GET /pins/1
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  def create
		@pin = current_user.pins.build(pin_params)
		if @pin.save
		  redirect_to @pin, notice: 'Pin was successfully created.'
		else
		  render :new
		end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
		if @pin.update(pin_params)
		  redirect_to @pin, notice: 'Pin was successfully updated.'
		else
		  render :edit
		end
	end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end
    
    def correct_user
	  	@pin = current_user.pins.find_by(id: params[:id])
	  	redirect_to pins_path, notice: "Not allowed to modify this pin" if @pin.nil?  
	  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pinteresting", root_path, :class => "navbar-brand" %>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact Info", contact_us_path %></li>
		  <li><%= link_to "Pricing", our_prices_path %></li>
		  <% if user_signed_in? %>
		  	<li><%= link_to "My Account", edit_user_registration_path %></li>
		  	<li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
		  <% else %>
		  	<li><%= link_to "Log In", new_user_session_path %></li>
		  <% end %>
		  
      </ul>
    </div><!-- /.navbar-collapse -->
	</div><!-- /.container --> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<%= render 'layouts/header' %>
   
	<div class="container">
		<% flash.each do |name, message| %>
			<% alert_class = "info" %>
			<% if name == "notice" 
					alert_class = "success"
				elsif name == "alert"
					alert_class = "danger"
				end
			%>
			<%= content_tag(:div, message, class: "alert alert-#{alert_class}") %> 
		<% end %>
		
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
   <h1>Welcome to my app!</h1>
   
   <% if user_signed_in? %>
   	<p>Welcome <%= current_user %></p>
   <% else %>
	   <p>
	      <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
			<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	  	</p>
  	<% end %>
  	    
</div>

app/views/pages/about.html.erb
<h1>About my application</h1>

<p>Hi there!</p>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>

<p>Hi. Please contact us if you have any problem.</p>

app/views/pages/home.html.erb
<div class="jumbotron center">
   <h1>Welcome to my app!</h1>
   
   <% if user_signed_in? %>
   	<p>Welcome <%= current_user %></p>
   <% else %>
	   <p>
	      <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
			<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	  	</p>
  	<% end %>
  	    
</div>

<footer>
	<%= link_to "About Us", about_path %>
</footer>

app/views/pages/pricing.html.erb
<h1>Pricing</h1>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Pinteresting Pricing</div>

  <!-- Table -->
  <table class="table">
	<th><td>Hej</td><td>Hoi</td></th> 
	<tr><td>Hej</td><td>Hoi</td></tr> 
  </table>
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' if !user_signed_in? %>

<% if user_signed_in? %>
	<%= link_to new_pin_path, class: "btn btn-primary" do %>
		<span class="glyphicon glyphicon-plus"></span> New Pin
	<% end %>
<% end %>
<br><br>

<div id="pins" class="transitions-enabled clear">
<% @pins.each do |pin| %>
	<div class="box panel panel-default">
	  <% my_image = image_tag pin.image.url(:medium) %>
	  <%= link_to my_image, pin %>
	  <div class="panel-body">
		  <%= pin.description %><br>
			<strong><%= pin.user.name if pin.user %></strong>
		  <% if pin.user == current_user %>
		  	<div class="actions">
			  	<%= link_to edit_pin_path(pin) do %>
			  		<span class="glyphicon glyphicon-edit"></span> Edit
			  	<% end %>
					<%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
						<span class="glyphicon glyphicon-trash"></span> Delete
					<% end %>
		  	</div>
		  <% end %>
	  </div>
	</div>
<% end %>
</div><!-- end #pins -->

<div class="clear"></div>

<div class="center">
   <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			
			<div class="panel-heading center">
				<%= image_tag @pin.image.url %>
			</div>
			
			<div class="panel-body">
				<p><%= @pin.description %></p>
        <p>by <strong><%= @pin.user.name if @pin.user %></strong></p>
				
				<% if @pin.user == current_user %>
					<%= link_to 'Edit', edit_pin_path(@pin) %> |
				<% end %>
			</div>
		</div>

	</div>
</div>